#!/bin/bash
# toggle keyboard layouts, list of two below; disables change by GUI panel 
LANG1="us,ru"
LANG2="ru,us"
# CURRENT_LANG=$(setxkbmap -query | tail -n 1 | cut -f6 -d ' ') # OLD LINE
CURRENT_LANG=$(setxkbmap -query | grep "layout" | cut -f6 -d ' ')
if [ "$CURRENT_LANG" = $LANG1 ]; then
    setxkbmap $LANG2,","
else
    setxkbmap $LANG1
fi